stages:
  - build
  - deploy

"Build Site":
  image:
    name: klakegg/hugo:0.59.1-ext-ubuntu
    entrypoint: [""]
  stage: build
  artifacts:
    paths:
    - public
  script:
    - hugo

deploy:
  stage: deploy
  image: instrumentisto/rsync-ssh:latest
  script:
  - mkdir "${HOME}/.ssh"
  - cp "${SSH_HOST_KEY}" "${HOME}/.ssh/known_hosts"
  - rsync -hrvz --delete --dry-run --exclude=_ -e 'ssh -i ${SSH_PRIVATE_KEY}' public/ "${SSH_USER_HOST_LOCATION}"
