stages:
  - build
  - deploy

"Build Site":
  image:
    name: klakegg/hugo:0.59.1-ext-ubuntu
    entrypoint: [""]
  stage: build
  artifacts:
    paths:
    - public
  script:
    - hugo

deploy:
  stage: deploy
  image: instrumentisto/rsync-ssh:588dd9a9e8a1f538038cc141ff4a58b9b205a828bb6b39d4a08b504b55aaea36
  script:
  - echo "${SSH_PRIVATE_KEY}" > id_rsa
  - chmod 700 id_rsa
  - mkdir "${HOME}/.ssh"
  - echo "${SSH_HOST_KEY}" > "${HOME}/.ssh/known_hosts"
  - rsync -hrvz --delete --exclude=_ -e 'ssh -i id_rsa -p 22' public/ "${SSH_USER_HOST_LOCATION}"
