baseurl = "http://bascht.com/"
languageCode = "de-de"

title = "bascht.com"
pygmentsStyle = "default"

[params]
locale = "de-DE"

[permalinks]
blog = "/blog/:year/:month/:day/:title/"
tech = "/tech/:year/:month/:day/:title/"

[indexes]
tag = "tags"


[[menu.main]]
name = "Vermietung"
weight = -110
url = "/rent-a-bascht/"
[[menu.main]]
name = "Blog"
weight = -100
url = "/blog/*"
[[menu.main]]
name = "Tech"
weight = -90
url = "/tech/"
[[menu.main]]
name = "Impressum"
weight = -80
url = "/impressum"
