baseurl = "https://bascht.com/"
MetaDataFormat = "yaml"
languageCode = "de-de"
defaultContentLanguage = "de"
enableEmoji = true

title = "bascht.com"
pygmentsStyle = "monokai"
PygmentsCodeFences = true
SectionPagesMenu = "main"

[markup.goldmark.renderer]
unsafe = true

[languages]
[languages.de]
[languages.en]

[params]
locale = "de-DE"
description = "Baschts home on the interwebs."

[permalinks]
blog = "/blog/:year/:month/:day/:title/"
tech = "/tech/:year/:month/:day/:title/"
posts = "/posts/:year/:month/:day/:slug/"

[indexes]
tag = "tags"

[menu]
[[menu.main]]
name = "Blog"
weight = -100
pageref = "/blog/"
identifier = "blog"
[[menu.main]]
name = "Tech"
weight = -90
pageref = "/tech/"
identifier = "tech"
[[menu.main]]
name = "Posts"
identifier = "posts"
weight = -95
pageref = "/posts/"
