baseurl = "https://bascht.com"
languageCode = "de-de"

title = "bascht.com"
pygmentsStyle = "monokai"
PygmentsCodeFences = true

[params]
locale = "de-DE"

[permalinks]
blog = "/blog/:year/:month/:day/:title/"
tech = "/tech/:year/:month/:day/:title/"

[indexes]
tag = "tags"


[[menu.main]]
name = "Blog"
weight = -100
url = "/blog/"
[[menu.main]]
name = "Tech"
weight = -90
url = "/tech/"
